[package]
name = "IRRL"
authors = ["James Ferney Rudas Marin <rudasmarinjf@gmail.com>"]
version = "1.0.0"
edition = "2024"

[dependencies]
rdev = "0.5"
enigo = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
rand = "0.8"
